application: jyf-pipe
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message
- mail

handlers:
- url: /((index|default)\.(html|htm|py|do|php|lua|rb))?
  static_files: index.html

- url: /static
  static_dir: static

- url: /_ah/xmpp/message/chat/
  script: xmpp_handler.py

- url: /_ah/mail/.+
  script: mail_handler.py

- url: /.*
  script: logic.py

